default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: svidlo
  password: 111111
  host: localhost

development:
  <<: *default
  database: development_trello

test:
  <<: *default
  database: test_trello
